language: java
jdk: openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - zmfl123097@gmail.com